config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  resources :users

  resources :comments, only: [:create, :destroy]
  resources :goods, only: [:create, :destroy]
  resources :bads, only: [:create, :destroy]
  resources :areas, only: [:show, :create, :new] 
  get 'search', to: 'areas#new'
end

app/models/area.rb
class Area < ApplicationRecord
validates :prefecture, presence: true

has_many :user
has_many :comments, dependent: :destroy
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :require_user_logged_in

  def new
  end

  def create
    @area = Area.find_by(id: params[:area][:prefecture])
    redirect_to area_path(@area)
  end
  
  def show
    @area = Area.find(params[:id])
    @y = y_day+3
    @myarea = weather_area(@area.lat.to_f, @area.lon.to_f)
    @comment = current_user.comments.build
    @comments = Comment.all.order(id: :desc).page(params[:page]).per(5)
    @comments_similar = Comment.where(
                      weather: @myarea["current"]["weather"][0]["main"]
                    ).where("temp <= #{similar_temp(1)}" 
                    ).where("temp >= #{similar_temp(-1)}"
                    ).where("humidity <= #{similar_humidity(10)}"
                    ).where("humidity >= #{similar_humidity(-10)}"
                    ).order(id: :desc).page(params[:page]).per(5)
  end
end

app/views/areas/new.erb
<div class= "row">
  <div class="col-sm-6 offset-sm-3">  
    <%= form_with(url: areas_path, scope: :area, local: true) do |f| %>
    <div class="form-group">
      <%= f.label :prefecture, "都道府県から検索" %>
      <%= f.collection_select :prefecture, Area.all, :id, :prefecture, {prompt: "選択してください"}, {class: "form-control"} %>
    </div>
      <%= f.submit "検索", class: "btn btn-primary btn-block"%>
    <% end %>
  </div>
</div>

app/views/areas/show.html.erb
  <%= render 'toppages/weather' %>
  <div class="mt-5">
    <div>
      <h5>今の気温と服装はどう？</h5>
      <%= form_with(model: @comment, local: true) do |f| %>
      <%= f.hidden_field :weather, :value => @myarea["current"]["weather"][0]["main"] %>
      <%= f.hidden_field :temp, :value => @myarea["current"]["temp"].to_i %>
      <%= f.hidden_field :humidity, :value => @myarea["current"]["humidity"] %>
      <%= f.hidden_field :area_id, :value => @area.id %>
        <div class="form-group row">
          <div class="col-sm-10">
            <%= f.text_area :content, class: 'form-control', rows: 1%>
          </div>
          <div class="col-sm-2">
            <%= f.submit '投稿', class: 'btn btn-primary btn-block' %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="mt-5">
      <h5>最近の投稿</h5>
      <%= render 'comments/comments', comments: @comments %>
    </div>
    <div class="mt-5">
      <h5>今と似た天気の時の投稿</h5>
      <% if @comments_similar.blank? %>
        <p>現在は投稿がありません。</p>
      <% end %>
      <%= render 'comments/comments', comments: @comments_similar %>
    </div>
  </div>